### ISSUE TITLE
Migration system

### ISSUE THREAD

**Issue by devmaster262** [bitcoin-api/miners-vip-doge#5]
It is important to honor the existing community by creating a system that allows for existing MineralsVIP NFTs to be ported to this new project. 

Qs to answer:
1) Are all rocks getting migrated?
2) How to pay the gas fees of migration?

**Comment by zentwist** [comment]
This is a complicated subject for a number of reasons. First of all, if you are migrating based on the amount held, those who know about this iteration of the project stand to gain a lot by buying under floor on the original project. I don't think that's very fair, personally. Is there a way to take a snapshot of another project? If so, maybe that should be done asap. Second, would it be easier to create a standardized OG token? Maybe with a value the encompasses the amount and rarity of the original minerals held?

**Comment by devmaster262** [comment]
> This is a complicated subject for a number of reasons. First of all, if you are migrating based on the amount held, those who know about this iteration of the project stand to gain a lot by buying under floor on the original project. I don't think that's very fair, personally. Is there a way to take a snapshot of another project? If so, maybe that should be done asap. Second, would it be easier to create a standardized OG token? Maybe with a value the encompasses the amount and rarity of the original minerals held?

I totally agree that allow given the floor price, letting people migrate their rocks for free or even for a low amount is unfair to people who are unable to buy at floor. Considering this is a new project, this can migration system can be turned into a marketing/ community engagement opportunity. 

Currently, there are ~1400 rocks. I think the migration system should be operational until 700 rocks exist in this new project. The migration system will be tiered. By tiered system what I mean is the first 100 get to migrate for 10% of the current minting cost, the next 200 get to migrate for 50% of the current minting cost, next 400 get to migrate for 75% of the current minting cost. Keep in mind while migration, someone can mine using the regular method and when 700 rocks exist within the new project, migration will be turned off. 
This does a couple of things:
1) incentivizes early adoption
2) creates buzz and could be a marketing opportunity
3) a LOT of rewards will be given out quickly since there will be demand to be an early migrator

**Comment by zentwist** [comment]
> > This is a complicated subject for a number of reasons. First of all, if you are migrating based on the amount held, those who know about this iteration of the project stand to gain a lot by buying under floor on the original project. I don't think that's very fair, personally. Is there a way to take a snapshot of another project? If so, maybe that should be done asap. Second, would it be easier to create a standardized OG token? Maybe with a value the encompasses the amount and rarity of the original minerals held?
> 
> I totally agree that allow given the floor price, letting people migrate their rocks for free or even for a low amount is unfair to people who are unable to buy at floor. Considering this is a new project, this can migration system can be turned into a marketing/ community engagement opportunity.
> 
> Currently, there are ~1400 rocks. I think the migration system should be operational until 700 rocks exist in this new project. The migration system will be tiered. By tiered system what I mean is the up to the first 100 people get to migrate for 10% of the current minting cost, then up to 200 get to migrate for 50% of the current minting cost, and then up to 400 get to migrate for 75% of the current minting cost. Keep in mind during migration, someone can mine using the regular method and when 700 rocks exist within the new project, migration will be turned off.
> This does a couple of things:
> 
> 1. incentivizes early adoption
> 2. creates buzz and could be a marketing opportunity
> 3. a LOT of rewards will be given out quickly since there will be demand to be an early migrator

Is there a way we could migrate without competing with each other for gas?

**Comment by devmaster262** [comment]
Could be so

**Comment by devmaster262** [comment]
A community suggestion was a batch migration to save gas. So here is a different proposal:
-  x days before the project release, the community will be given the option to transfer up 512 MinersVIP NFTS to a dev address
- On project release or a little while before, those that transferred their NFT will be sent this project's version of the NFT with the same revenue share 
- The project will essentially start with 512 rocks mined. This will also mean that the minting cost will reflect the fact that 512 rocks exist.

**Comment by zentwist** [comment]
That sounds great. Is there a way to do a random draw of the original holders to determine who gets the free 512? A first come first serve implementation would likely lead to most people being left out while larger stakeholder reap the majority of the benefits.

**Comment by bitcoin-api** [comment]
People will keep their rocks, end of discussion
